
service: lambda-auth # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

functions:
  test:
    handler: handler.test
    integration: lambda   
    events:
      - http:
          path: /
          method: get
          authorizer: auth
          cors: true
  auth:
    handler: handler.auth

