
service: lambda-auth 

provider:
  name: aws
  runtime: nodejs6.10

functions:
  test:
    handler: functions/handler.test
    integration: lambda   
    events:
      - http:
          path: /
          method: get
          authorizer: auth
          cors: true
  auth:
    handler: functions/authorization.auth

